import type { CreateJobInput } from "@/types/job";

export const cloudDataArchitectJob: Omit<CreateJobInput, "employer_id"> = {
  title: "Cloud Data Architect",
  subtitle: "Google Cloud & BigQuery",
  slug: "cloud-data-architect",
  company_display: "bejoby",
  description: "As a Cloud Data Architect at bejoby, you will define and lead the architecture of our enterprise data platform on Google Cloud. You will work closely with business, engineering, QA, and data teams to turn organizational goals into secure, scalable, high-performing, and cost-efficient data solutions.",
  location: "Remote",
  salary_range: "Based on expected monthly rate",
  seniority: "Senior / Lead",
  experience_years: "5+",
  employment_type: "contract",
  work_mode: "remote",
  language: "en",
  status: "published",
  stack: {
    cloud: ["Google Cloud", "BigQuery", "Cloud Storage", "IAM", "Cloud KMS"],
    data: ["Data modeling", "Semantic layers", "Data quality", "Data governance", "Data lineage"],
  },
  requirements_mandatory: [
    "Bachelor's degree in Computer Science, Software Engineering, or a related field.",
    "Strong expertise designing scalable, secure, and cost-efficient data architectures on Google Cloud, with a primary focus on BigQuery.",
    "Advanced knowledge of BigQuery partitioning, clustering, materialized views, query tuning, and storage lifecycle management.",
    "Experience designing enterprise data models and semantic layers for analytics, reporting, BI, marketing optimization, and data science.",
    "Knowledge of master and reference data management practices across multiple data domains.",
    "Experience defining automated data quality frameworks, validation controls, reconciliation processes, and integrity checks.",
    "Understanding of IAM, encryption, metadata administration, data governance, and data lineage.",
    "Experience designing end-to-end enterprise data architectures, integration plans, UAT, and production rollout strategies.",
    "Upper Intermediate (B2) or Proficient (C1) English.",
  ],
  responsibilities: [
    "Define and lead the end-to-end architecture of the Google Cloud BigQuery platform.",
    "Establish strategies that improve BigQuery query performance and optimize infrastructure costs.",
    "Create enterprise data models and semantic structures aligned with analytical and business requirements.",
    "Partner with executives and business stakeholders to translate organizational goals into measurable technical solutions.",
    "Establish master and reference data approaches that promote reliable, consistent, and governed information.",
    "Drive automation of data quality through transformation logic, validation, reconciliation, and automated controls.",
    "Partner with QA teams to evaluate test scenarios, business coverage, and data quality outcomes.",
    "Coordinate integration, UAT, deployment, production cutover, fallback, and contingency activities across teams.",
    "Define and enforce access management, encryption, metadata, and data lineage practices.",
    "Monitor BigQuery utilization and continuously balance performance, storage, and cost.",
    "Produce and maintain enterprise data architecture blueprints and deployment plans.",
  ],
  soft_skills: ["Responsibility", "Proactivity", "Flexibility", "Great communication skills"],
  what_we_offer: [
    "Work on high-impact AI and data products with an experienced, collaborative team.",
    "Remote work and flexible collaboration across international teams.",
    "The opportunity to shape enterprise data architecture from strategy through production.",
  ],
  search_tags: ["cloud data architect", "google cloud", "gcp", "bigquery", "data architecture", "data governance", "remote"],
};
